let infosPlanetas = [
  {
    planeta: "Mercúrio",
    descricao: "O planeta mais próximo do Sol, Mercúrio é o menor planeta do Sistema Solar e não possui luas. Sua superfície é marcada por crateras e planícies, semelhante à da Lua.",
    luas: "Sem luas",
    composicao: "Superfície rochosa com ferro no núcleo",
    link: "https://pt.wikipedia.org/wiki/Merc%C3%BArio_(planeta)",
    tags: "próximo sol menor crateras",
  },
  {
    planeta: "Vênus",
    descricao: "O segundo planeta mais próximo do Sol, Vênus é conhecido como o planeta mais quente do Sistema Solar. Sua atmosfera densa é composta principalmente de dióxido de carbono, e sua superfície é marcada por vulcões e montanhas.",
    luas: "Sem luas",
    composicao: "Superfície rochosa com atmosfera densa de dióxido de carbono",
    link: "https://pt.wikipedia.org/wiki/V%C3%A9nus_(planeta)",
    tags: "quente atmosfera densa vulcões",
  },
  {
    planeta: "Terra",
    descricao: "O terceiro planeta a partir do Sol e o único conhecido por abrigar vida, a Terra é um planeta rochoso com uma atmosfera rica em oxigênio. Possui um grande oceano global e um satélite natural, a Lua.",
    luas: "Lua",
    composicao: "Superfície rochosa com atmosfera rica em nitrogênio e oxigênio",
    link: "https://pt.wikipedia.org/wiki/Terra",
    tags: "vida oceano lua",
  },
  {
    planeta: "Marte",
    descricao: "Conhecido como o 'Planeta Vermelho', Marte é um planeta rochoso com uma atmosfera fina composta principalmente de dióxido de carbono. Possui duas pequenas luas, Fobos e Deimos.",
    luas: "Fobos e Deimos",
    composicao: "Superfície rochosa com dióxido de carbono na atmosfera",
    link: "https://pt.wikipedia.org/wiki/Marte",
    tags: "vermelho atmosfera fina",
  },
  {
    planeta: "Júpiter",
    descricao: "O maior planeta do nosso sistema solar, Júpiter é um gigante gasoso composto principalmente de hidrogênio e hélio. Conhecido por sua Grande Mancha Vermelha, uma tempestade maior que a Terra, Júpiter possui dezenas de luas e um poderoso campo magnético.",
    luas: "Ganimedes, Io, Europa, Calisto (e mais 75 luas)",
    composicao: "Hidrogênio e hélio",
    link: "https://pt.wikipedia.org/wiki/J%C3%BApiter_(planeta)",
    tags: "gasoso maior hidrogenio hidrogênio helio hélio mancha",
  },
  {
    planeta: "Saturno",
    descricao: "Famoso por seus anéis espetaculares, Saturno é outro gigante gasoso composto principalmente de hidrogênio e hélio. Seus anéis são formados por bilhões de partículas de gelo e rocha. Saturno também possui muitas luas, incluindo Titã, a maior lua de Saturno e a segunda maior do Sistema Solar.",
    luas: "Titã, Encélado (e mais 80 luas)",
    composicao: "Hidrogênio e hélio",
    link: "https://pt.wikipedia.org/wiki/Saturno_(planeta)",
    tags: "gasoso hidrogenio hidrogênio helio hélio anéis aneis",
  },
  {
    planeta: "Urano",
    descricao: "Urano é um gigante gasoso com uma coloração azul-esverdeada causada pela presença de metano em sua atmosfera. O planeta é notável por seu eixo de rotação extremamente inclinado, o que faz com que ele 'role' ao longo de sua órbita. Urano possui anéis tênues e várias luas.",
    luas: "Miranda, Ariel, Umbriel, Titânia, Oberon (e mais 22 luas)",
    composicao: "Hidrogênio, hélio e metano",
    link: "https://pt.wikipedia.org/wiki/Urano_(planeta)",
    tags: "metano inclinado anéis azulado",
  },
  {
    planeta: "Netuno",
    descricao: "O planeta mais distante do Sol, Netuno é um gigante gasoso gelado com ventos extremamente fortes. Sua cor azul intensa é causada pelo metano em sua atmosfera. Netuno possui um sistema de anéis mais fraco que o de Saturno e várias luas.",
    luas: "Tritão, Proteu, Nereida (e mais 11 luas)",
    composicao: "Hidrogênio, hélio e metano",
    link: "https://pt.wikipedia.org/wiki/Netuno_(planeta)",
    tags: "distante frio ventos azul",
  },
];
